spring:
  profiles:
    active: @env.id@
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  application:
    name: example-job
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # 文件大小限制
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  # redis token信息
  redis:
    key:
      prefix:
        userToken: "user:token:"
        passwordError: "user:password:error:"
        permissionRefresh: "user:token:permissionRefresh:"
      expire:
        userToken: 604800 # 7天 7*24*3600
        passwordError: 3600 # 一个小时
        permissionRefresh: 604800 # 7天 7*24*3600
    allowMultipleLogin: true # 允许多处登录
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update # Hibernate ddl auto (create, create-drop, validate, update)



#每天凌晨12点排序处理
job:
  order_complete:
    cron: 0 0 0/1 * * ?
