server:
  # 服务端口
  port: 8081
spring:
  application:
    name: order-provider
# dubbo 相关配置(dubbo 的配置不再以 Spring 开头)
dubbo:
  application:
    # 应用名称
    name: order-provider
  scan:
    # 接口实现者（服务实现）包
    base-packages: com.xiushang.admin.service
  # 注册中心信息
  registry:
    address: zookeeper://192.168.29.12:2181
  protocol:
    # 协议名称
    name: dubbo
    # 协议端口
    port: 20880
