# 端口
server:
  port: 80
  servlet:
    register-default-servlet: true

# dubbo 相关配置
dubbo:
  application:
    name: admin-consumer
  registry:
    address: zookeeper://192.168.29.12:2181

spring:
  profiles:
    active: @env.id@
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  application:
    name: xiushang-admin
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # 文件大小限制
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  # redis token信息
  redis:
    key:
      prefix:
        userToken: "user:token:"
        passwordError: "user:password:error:"
        permissionRefresh: "user:token:permissionRefresh:"
      expire:
        userToken: 604800 # 7天 7*24*3600
        passwordError: 3600 # 一个小时
        permissionRefresh: 604800 # 7天 7*24*3600
    allowMultipleLogin: true # 允许多处登录
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update # Hibernate ddl auto (create, create-drop, validate, update)

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  # 关闭spring data 的redis仓库
  data:
    redis:
      repositories:
        enabled: false

knife4j:
  enable: true
  setting:
    enableFooter: false
    enableFooterCustom: true
    footerCustomContent: Apache License 2.0 | Copyright ©️ 2021 秀上

#定时任务
job:
  order_complete:
    cron: 0 0 0/1 * * ?
#------------ sms ------------
#短信模板和签名
sms:
  signName: xxxxxxxxxxxx
  templateCode: xxxxxxxxxxxx
  accessKeyId:  xxxxxxxxxxxx
  accessKeySecret:  xxxxxxxxxxxx
  templateCodeTip:  xxxxxxxxxxxx
  templateCodeOrderTip: xxxxxxxxxxxx
  templateCodeIntegralOrderTip: xxxxxxxxxxxx
  templateCodeEnrollTip:  xxxxxxxxxxxx
  adminCode:  xxxxxxxxxxxx

#微信授权key
weixin:
  appid:  xxxxxxxxxxxx
  secret: xxxxxxxxxxxx

#ftp
ftp:
  port: 21
  hostname: xxx:xxx:xxx:xxx
  username: xxxxxxFtp
  password: xxxxxxxxxxxx

#jwt whitelist
jwt:
  ignored:
    urls: #安全路径白名单
      - /
      - /doc.html
      - /swagger-resources/**
      - /v2/api-docs
      - /v2/api-docs-ext
      - /webjars/**
      #- /druid/**
      - /favicon.ico
      - /favicon.png
      - /test/**
      - /captcha.jpg
      - /authentication/**
      - /oauthLogin
      #- static
      - /**/*.js
      - /**/*.css
      - /**/*.html
      - /**/*.jpg
      - /**/*.jpeg
      - /**/*.png
      - /**/favicon.ico
      - /**/*.apk
      - /**/*.txt

#oauth path
oauth:
  client: #管理员客户端前缀
    prex: xiushang
  path:
    url: /api/

